// packages/angular-sdk/projects/video-angular-sdk/src/lib/device-settings/device-settings.component.ts
import { Component, OnInit } from '@angular/core';
import {
  Call,
  getAudioDevices,
  getAudioOutputDevices,
  getAudioStream,
  getVideoDevices,
  getVideoStream,
  checkIfAudioOutputChangeSupported,
} from '@stream-io/video-client';
import { Observable, Subscription } from 'rxjs';
import { StreamVideoService } from '../video.service';
import { NgxPopperjsTriggers } from 'ngx-popperjs';

@Component({
  selector: 'stream-device-settings',
  templateUrl: './device-settings.component.html',
  styles: [],
})
export class DeviceSettingsComponent implements OnInit {
  currentlyUsedAudioDeviceId?: string;
  currentlyUsedVideoDeviceId?: string;
  currentlyUsedAudioOutputDeviceId?: string;
  audioDevices$: Observable<MediaDeviceInfo[]>;
  videoDevices$: Observable<MediaDeviceInfo[]>;
  audioOutputDevices$: Observable<MediaDeviceInfo[]>;
  popperTrigger = NgxPopperjsTriggers.click;
  isAudioOuputDeviceChangeSupported = checkIfAudioOutputChangeSupported();
  private activeCall?: Call;
  private subscriptions: Subscription[] = [];

  constructor(private streamVideoService: StreamVideoService) {
    this.subscriptions.push(
      this.streamVideoService.activeCall$.subscribe(
        (c) => (this.activeCall = c),
      ),
    );
    this.subscriptions.push(
      this.streamVideoService.activeCallLocalParticipant$.subscribe((p) => {
        this.currentlyUsedAudioDeviceId = p?.audioDeviceId;
        this.currentlyUsedVideoDeviceId = p?.videoDeviceId;
        this.currentlyUsedAudioOutputDeviceId = p?.audioOutputDeviceId;
      }),
    );
    this.audioDevices$ = getAudioDevices();
    this.videoDevices$ = getVideoDevices();
    this.audioOutputDevices$ = getAudioOutputDevices();
  }

  ngOnInit(): void {}

  async changeInputDevice(
    kind: Exclude<MediaDeviceKind, 'audiooutput'>,
    event: any,
  ) {
    const deviceId = event.target.value;
    try {
      const mediaStream = await (kind === 'audioinput'
        ? getAudioStream(deviceId)
        : getVideoStream(deviceId));
      this.activeCall?.replaceMediaStream(kind, mediaStream);
    } catch (error) {
      console.error(`Error during device changing`, error);
      throw error;
    }
  }

  async changeOutputDevice(event: any) {
    const deviceId = event.target.value;
    this.activeCall?.setAudioOutputDevice(deviceId);
  }
}

<span
  [popper]="deviceSettings"
  [popperTrigger]="popperTrigger"
  class="str-video__device-settings__icon"
  tabindex="0"
></span>
<popper-content #deviceSettings>
  <div
    class="str-video__device-settings"
  >
    <div class="str-video__device-settings__device-kind">
      <div class="str-video__device-settings__device-selector-label">
        Select camera
      </div>
      <select
        class="str-video__device-settings__device-selector"
        [value]="currentlyUsedVideoDeviceId"
        (change)="changeInputDevice('videoinput', $event)"
      >
        <option
          *ngFor="let device of videoDevices$ | async"
          [value]="device.deviceId"
        >
          {{ device.label }}
        </option>
      </select>
    </div>
    <div class="str-video__device-settings__device-kind">
      <div class="str-video__device-settings__device-selector-label">
        Select mic
      </div>
      <select
        class="str-video__device-settings__device-selector"
        [value]="currentlyUsedAudioDeviceId"
        (change)="changeInputDevice('audioinput', $event)"
      >
        <option
          *ngFor="let device of audioDevices$ | async"
          [value]="device.deviceId"
        >
          {{ device.label }}
        </option>
      </select>
    </div>
    <div *ngIf="isAudioOuputDeviceChangeSupported" class="str-video__device-settings__device-kind">
      <div class="str-video__device-settings__device-selector-label">
        Select audio output
      </div>
      <select
        class="str-video__device-settings__device-selector"
        [value]="currentlyUsedAudioOutputDeviceId"
        (change)="changeOutputDevice($event)"
      >
        <option
          *ngFor="let device of audioOutputDevices$ | async"
          [value]="device.deviceId"
        >
          {{ device.label }}
        </option>
      </select>
    </div>
  </div>
</popper-content>

// packages/react-sdk/src/components/StreamCall/DeviceSettings.tsx
import { Call } from '@stream-io/video-client';
import { useLocalParticipant } from '@stream-io/video-react-bindings';
import { useState } from 'react';
import { usePopper } from 'react-popper';
import { useMediaDevices } from '../../contexts/MediaDevicesContext';

export const DeviceSettings = (props: { activeCall: Call }) => {
  const { activeCall } = props;
  const {
    audioDevices,
    videoDevices,
    audioOutputDevices,
    isAudioOutputChangeSupported,
    getAudioStream,
    getVideoStream,
  } = useMediaDevices();

  const [referenceElement, setReferenceElement] =
    useState<HTMLSpanElement | null>(null);
  const [popperElement, setPopperElement] = useState<HTMLDivElement | null>(
    null,
  );
  const { styles, attributes } = usePopper(referenceElement, popperElement);
  const [isPopperOpen, setIsPopperOpen] = useState(false);

  const localParticipant = useLocalParticipant();

  const switchDevice = async (
    kind: 'videoinput' | 'audioinput',
    deviceId: string,
  ) => {
    const mediaStream = await (kind === 'videoinput'
      ? getVideoStream(deviceId)
      : getAudioStream(deviceId));
    activeCall.replaceMediaStream(kind, mediaStream);
  };

  const setAudioOutputDevice = (deviceId: string) => {
    activeCall?.setAudioOutputDevice(deviceId);
  };

  return (
    <>
      <span
        className="str-video__device-settings__icon"
        tabIndex={0}
        ref={setReferenceElement}
        onClick={() => {
          setIsPopperOpen((v) => !v);
        }}
      />
      {isPopperOpen && (
        <div
          className="str-video__device-settings"
          ref={setPopperElement}
          style={styles.popper}
          {...attributes.popper}
        >
          <DeviceSelector
            devices={videoDevices}
            label="Select a Camera"
            selectedDeviceId={localParticipant?.videoDeviceId}
            onChange={(deviceId) => {
              switchDevice('videoinput', deviceId);
            }}
          />
          <DeviceSelector
            devices={audioDevices}
            label="Select a Mic"
            selectedDeviceId={localParticipant?.audioDeviceId}
            onChange={(deviceId) => {
              switchDevice('audioinput', deviceId);
            }}
          />
          {isAudioOutputChangeSupported && (
            <DeviceSelector
              devices={audioOutputDevices}
              label="Select audio output"
              selectedDeviceId={localParticipant?.audioOutputDeviceId}
              onChange={(deviceId) => {
                setAudioOutputDevice(deviceId);
              }}
            />
          )}
        </div>
      )}
    </>
  );
};

export const DeviceSelector = (props: {
  devices: MediaDeviceInfo[];
  selectedDeviceId?: string;
  label: string;
  onChange?: (deviceId: string) => void;
}) => {
  const { devices, selectedDeviceId, label, onChange } = props;
  return (
    <div className="str-video__device-settings__device-kind">
      <div className="str-video__device-settings__device-selector-label">
        {label}
      </div>
      <select
        className="str-video__device-settings__device-selector"
        value={selectedDeviceId}
        onChange={(e) => {
          onChange?.(e.target.value);
        }}
      >
        {devices.map((device) => (
          <option key={device.deviceId} value={device.deviceId}>
            {device.label}
          </option>
        ))}
      </select>
    </div>
  );
};
