// packages/angular-sdk/projects/video-angular-sdk/src/lib/stage/stage.component.ts
import { Component, OnInit } from '@angular/core';
import { StreamVideoParticipant } from '@stream-io/video-client';
import { Observable } from 'rxjs';
import { StreamVideoService } from '../video.service';

@Component({
  selector: 'stream-stage',
  templateUrl: './stage.component.html',
  styles: [],
})
export class StageComponent implements OnInit {
  participants$: Observable<StreamVideoParticipant[]>;
  localParticipant$: Observable<StreamVideoParticipant | undefined>;

  constructor(private streamVideoService: StreamVideoService) {
    this.participants$ = this.streamVideoService.remoteParticipants$;
    this.localParticipant$ = this.streamVideoService.localParticipant$;
  }

  ngOnInit(): void {}

  trackByParticipantId(_: number, item: StreamVideoParticipant) {
    return item.userId || undefined + item.sessionId;
  }
}

<div class="str-video__stage">
  <div class="str-video__call-participants-view str-video__grid-{{ (participants$ | async)!.length + 1 }}">
    <stream-participant
      [participant]="(localParticipant$ | async)!"
    ></stream-participant>
    <stream-participant
      *ngFor="
        let participant of participants$ | async;
        trackBy: trackByParticipantId
      "
      [participant]="participant"
    ></stream-participant>
  </div>
</div>

// packages/react-sdk/src/components/StreamCall/Stage.tsx
import { SfuModels } from '@stream-io/video-client';
import { Call } from '@stream-io/video-client';
import {
  useLocalParticipant,
  useRemoteParticipants,
} from '@stream-io/video-react-bindings';

import { useStage } from '../../hooks';

import { ParticipantBox } from './ParticipantBox';

export const Stage = ({
  call,
}: {
  call: Call;
  participants: SfuModels.Participant[];
}) => {
  const localParticipant = useLocalParticipant();
  const remoteParticipants = useRemoteParticipants();

  const { updateVideoSubscriptionForParticipant } = useStage(call);

  const grid = `str-video__grid-${remoteParticipants.length + 1 || 1}`;
  return (
    <div className={`str-video__stage ${grid}`}>
      {localParticipant && (
        <ParticipantBox
          participant={localParticipant}
          isMuted
          call={call}
          sinkId={localParticipant?.audioOutputDeviceId}
          updateVideoSubscriptionForParticipant={
            updateVideoSubscriptionForParticipant
          }
        />
      )}

      {remoteParticipants.map((participant) => (
        <ParticipantBox
          key={participant.sessionId}
          participant={participant}
          call={call}
          sinkId={localParticipant?.audioOutputDeviceId}
          updateVideoSubscriptionForParticipant={
            updateVideoSubscriptionForParticipant
          }
        />
      ))}
    </div>
  );
};
