// packages/components/src/components/StreamCall/CallControls.tsx
import clsx from 'clsx';
import { Call } from '@stream-io/video-client-sfu';
import { useMediaDevices } from '../../contexts/MediaDevicesContext';
import { useMuteState } from '../../hooks/useMuteState';
export const CallControls = (props: { call: Call }) => {
  const { call } = props;
  const { audioStream, videoStream } = useMediaDevices();
  const isAudioMute = useMuteState(call, audioStream?.getAudioTracks()[0]);
  const isVideoMute = useMuteState(call, videoStream?.getVideoTracks()[0]);

  return (
    <div className="str-video__call-controls">
      <Button
        icon={isAudioMute ? 'mic-off' : 'mic'}
        onClick={() => {
          call.updateMuteState('audio', !isAudioMute);
        }}
      />
      <Button
        icon={isVideoMute ? 'camera-off' : 'camera'}
        onClick={() => {
          call.updateMuteState('video', !isVideoMute);
        }}
      />
      <Button
        icon="call-end"
        variant="danger"
        onClick={() => {
          call.leave();
          // FIXME: OL: move this away from here
          alert('Call ended. You may close the window now.');
        }}
      />
    </div>
  );
};

const Button = (props: {
  icon: string;
  variant?: string;
  onClick?: () => void;
}) => {
  const { icon, variant, onClick } = props;
  return (
    <a
      href="#"
      onClick={(e) => {
        e.preventDefault();
        onClick?.();
      }}
      className={clsx(
        'str-video__call-controls__button',
        icon && `str-video__call-controls__button--icon-${icon}`,
        variant && `str-video__call-controls__button--variant-${variant}`,
      )}
    />
  );
};

// packages/angular-sdk/projects/video-angular-sdk/src/lib/call-controls/call-controls.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {
  StreamVideoParticipant,
  Call,
  SfuModels,
} from '@stream-io/video-client';

@Component({
  selector: 'stream-call-controls',
  templateUrl: './call-controls.component.html',
  styles: [],
})
export class CallControlsComponent implements OnInit {
  @Input() localParticipant?: StreamVideoParticipant;
  @Input() call?: Call;

  TrackKind = SfuModels.TrackKind;

  ngOnInit(): void {}

  updateAudioMuteState() {
    console.warn(
      this.call,
      !this.localParticipant?.publishedTracks.includes(
        SfuModels.TrackKind.AUDIO,
      ),
    );
    this.call?.updateMuteState(
      'audio',
      !!this.localParticipant?.publishedTracks.includes(
        SfuModels.TrackKind.AUDIO,
      ),
    );
  }

  updateVideoMuteState() {
    this.call?.updateMuteState(
      'video',
      !!this.localParticipant?.publishedTracks.includes(
        SfuModels.TrackKind.VIDEO,
      ),
    );
  }

  endCall() {
    this.call?.leave();
  }
}

<div class="str-video__call-controls">
  <button
    class="str-video__call-controls__button"
    [ngClass]="{
      'str-video__call-controls__button--icon-mic':
        localParticipant?.publishedTracks?.includes(TrackKind.AUDIO),
      'str-video__call-controls__button--icon-mic-off':
        !localParticipant?.publishedTracks?.includes(TrackKind.AUDIO)
    }"
    (click)="updateAudioMuteState()"
  ></button>
  <button
    class="str-video__call-controls__button"
    [ngClass]="{
      'str-video__call-controls__button--icon-camera':
        localParticipant?.publishedTracks?.includes(TrackKind.VIDEO),
      'str-video__call-controls__button--icon-camera-off':
        !localParticipant?.publishedTracks?.includes(TrackKind.VIDEO)
    }"
    (click)="updateVideoMuteState()"
  ></button>
  <button
    class="str-video__call-controls__button str-video__call-controls__button--icon-call-end str-video__call-controls__button--variant-danger"
    (click)="endCall()"
  ></button>
</div>
