// packages/react-sdk/src/components/StreamCall/CallControls.tsx
import clsx from 'clsx';
import { ForwardedRef, forwardRef, useRef, useState } from 'react';
import { Call, CallMeta, SfuModels } from '@stream-io/video-client';
import {
  useLocalParticipant,
  useStreamVideoClient,
  useIsCallRecordingInProgress,
} from '@stream-io/video-react-bindings';
import { CallStats } from './CallStats';

export const CallControls = (props: {
  call: Call;
  callMeta?: CallMeta.Call;
}) => {
  const { call, callMeta } = props;
  const client = useStreamVideoClient();
  const isCallRecordingInProgress = useIsCallRecordingInProgress();
  const localParticipant = useLocalParticipant();
  const isAudioMute = !localParticipant?.publishedTracks.includes(
    SfuModels.TrackKind.AUDIO,
  );
  const isVideoMute = !localParticipant?.publishedTracks.includes(
    SfuModels.TrackKind.VIDEO,
  );

  const [isStatsOpen, setIsStatsOpen] = useState(false);
  const statsAnchorRef = useRef<HTMLButtonElement>(null);

  return (
    <div className="str-video__call-controls">
      <Button
        icon={isCallRecordingInProgress ? 'recording-on' : 'recording-off'}
        title="Record call"
        onClick={() => {
          if (!callMeta) return;
          if (isCallRecordingInProgress) {
            client?.stopRecording(callMeta.id, callMeta.type);
          } else {
            client?.startRecording(callMeta.id, callMeta.type);
          }
        }}
      />
      {isStatsOpen && (
        <CallStats
          anchor={statsAnchorRef.current!}
          onClose={() => {
            setIsStatsOpen(false);
          }}
        />
      )}
      <Button
        icon="stats"
        title="Statistics"
        ref={statsAnchorRef}
        onClick={() => {
          setIsStatsOpen((v) => !v);
        }}
      />
      <Button
        icon={isAudioMute ? 'mic-off' : 'mic'}
        onClick={() => {
          call.updateMuteState('audio', !isAudioMute);
        }}
      />
      <Button
        icon={isVideoMute ? 'camera-off' : 'camera'}
        onClick={() => {
          call.updateMuteState('video', !isVideoMute);
        }}
      />
      <Button
        icon="call-end"
        variant="danger"
        onClick={() => {
          call.leave();
          // FIXME: OL: move this away from here
          alert('Call ended. You may close the window now.');
        }}
      />
    </div>
  );
};

const Button = forwardRef(
  (
    props: {
      icon: string;
      variant?: string;
      onClick?: () => void;
      [anyProp: string]: any;
    },
    ref: ForwardedRef<HTMLButtonElement>,
  ) => {
    const { icon, variant, onClick, ...rest } = props;
    return (
      <button
        onClick={(e) => {
          e.preventDefault();
          onClick?.();
        }}
        className={clsx(
          'str-video__call-controls__button',
          icon && `str-video__call-controls__button--icon-${icon}`,
          variant && `str-video__call-controls__button--variant-${variant}`,
        )}
        ref={ref}
        {...rest}
      />
    );
  },
);

// packages/angular-sdk/projects/video-angular-sdk/src/lib/call-controls/call-controls.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {
  StreamVideoParticipant,
  Call,
  SfuModels,
} from '@stream-io/video-client';

@Component({
  selector: 'stream-call-controls',
  templateUrl: './call-controls.component.html',
  styles: [],
})
export class CallControlsComponent implements OnInit {
  @Input() localParticipant?: StreamVideoParticipant;
  @Input() call?: Call;

  TrackKind = SfuModels.TrackKind;

  ngOnInit(): void {}

  updateAudioMuteState() {
    console.warn(
      this.call,
      !this.localParticipant?.publishedTracks.includes(
        SfuModels.TrackKind.AUDIO,
      ),
    );
    this.call?.updateMuteState(
      'audio',
      !!this.localParticipant?.publishedTracks.includes(
        SfuModels.TrackKind.AUDIO,
      ),
    );
  }

  updateVideoMuteState() {
    this.call?.updateMuteState(
      'video',
      !!this.localParticipant?.publishedTracks.includes(
        SfuModels.TrackKind.VIDEO,
      ),
    );
  }

  endCall() {
    this.call?.leave();
  }
}

<div class="str-video__call-controls">
  <button
    class="str-video__call-controls__button"
    [ngClass]="{
      'str-video__call-controls__button--icon-mic':
        localParticipant?.publishedTracks?.includes(TrackKind.AUDIO),
      'str-video__call-controls__button--icon-mic-off':
        !localParticipant?.publishedTracks?.includes(TrackKind.AUDIO)
    }"
    (click)="updateAudioMuteState()"
  ></button>
  <button
    class="str-video__call-controls__button"
    [ngClass]="{
      'str-video__call-controls__button--icon-camera':
        localParticipant?.publishedTracks?.includes(TrackKind.VIDEO),
      'str-video__call-controls__button--icon-camera-off':
        !localParticipant?.publishedTracks?.includes(TrackKind.VIDEO)
    }"
    (click)="updateVideoMuteState()"
  ></button>
  <button
    class="str-video__call-controls__button str-video__call-controls__button--icon-call-end str-video__call-controls__button--variant-danger"
    (click)="endCall()"
  ></button>
</div>
